// @flow
export const HOME_PAGE_ADD_HEADER_ROW = 'HOME_PAGE_ADD_HEADER_ROW';
export const HOME_PAGE_REMOVE_HEADER_ROW = 'HOME_PAGE_REMOVE_HEADER_ROW';
export const HOME_PAGE_HEADER_EDIT_KEY = 'HOME_PAGE_HEADER_EDIT_KEY';
export const HOME_PAGE_HEADER_EDIT_VAL = 'HOME_PAGE_HEADER_EDIT_VAL';
export const HOME_PAGE_SCHEME_ADD_ROW = 'HOME_PAGE_SCHEME_ADD_ROW';
export const HOME_PAGE_SCHEME_REMOVE_ROW = 'HOME_PAGE_SCHEME_REMOVE_ROW';
export const HOME_PAGE_SCHEME_EDIT_KEY = 'HOME_PAGE_SCHEME_EDIT_KEY';
export const HOME_PAGE_SCHEME_EDIT_VAL = 'HOME_PAGE_SCHEME_EDIT_VAL';
export const HOME_PAGE_CHOOSE_METHOD = 'HOME_PAGE_CHOOSE_METHOD';
export const HOME_PAGE_CHOOSE_FETCH_METHOD = 'HOME_PAGE_CHOOSE_FETCH_METHOD';
export const HOME_PAGE_CHOOSE_LOCALE = 'HOME_PAGE_CHOOSE_LOCALE';
export const HOME_PAGE_EDIT_URL = 'HOME_PAGE_EDIT_URL';
export const HOME_PAGE_SEND = 'HOME_PAGE_SEND';
export const HOME_PAGE_SEND_FAIL = 'HOME_PAGE_SEND_FAIL';
export const HOME_PAGE_SEND_CHOOSE_N = 'HOME_PAGE_SEND_CHOOSE_N';
export const HOME_PAGE_CLEAR_RESULT = 'HOME_PAGE_CLEAR_RESULT';
